from dataclasses import dataclass, field
from typing import Dict, List, Optional, Any
from datetime import datetime
import uuid


@dataclass
class DocusaurusPage:
    """
    Represents a crawled page from a Docusaurus site.
    """
    url: str
    title: str = ""
    content: str = ""
    html_content: Optional[str] = None
    last_modified: datetime = field(default_factory=datetime.now)
    status_code: int = 200
    error_message: Optional[str] = None

    def __post_init__(self):
        """Validate required fields after initialization."""
        if not self.url:
            raise ValueError("URL is required for DocusaurusPage")


@dataclass
class TextChunk:
    """
    Represents a segment of text prepared for embedding.
    """
    chunk_id: str
    original_url: str
    content: str
    start_pos: int
    end_pos: int
    section_title: Optional[str] = None
    chunk_metadata: Dict[str, Any] = field(default_factory=dict)

    def __post_init__(self):
        """Validate required fields after initialization."""
        if not self.chunk_id:
            raise ValueError("chunk_id is required for TextChunk")
        if not self.original_url:
            raise ValueError("original_url is required for TextChunk")
        if not self.content:
            raise ValueError("content is required for TextChunk")
        if self.start_pos < 0 or self.end_pos < 0:
            raise ValueError("start_pos and end_pos must be non-negative")
        if self.start_pos > self.end_pos:
            raise ValueError("start_pos must be less than or equal to end_pos")


@dataclass
class EmbeddingVector:
    """
    Represents a semantic vector generated by Cohere.
    """
    vector_id: str
    chunk_id: str
    embedding: List[float]
    size: int
    created_at: datetime = field(default_factory=datetime.now)

    def __post_init__(self):
        """Validate required fields after initialization."""
        if not self.vector_id:
            raise ValueError("vector_id is required for EmbeddingVector")
        if not self.chunk_id:
            raise ValueError("chunk_id is required for EmbeddingVector")
        if not self.embedding:
            raise ValueError("embedding is required for EmbeddingVector")
        if self.size <= 0:
            raise ValueError("size must be positive for EmbeddingVector")
        if len(self.embedding) != self.size:
            raise ValueError("embedding length must match size")


@dataclass
class StorageRecord:
    """
    Represents the stored entry in Qdrant with metadata.
    """
    qdrant_point_id: str
    payload: Dict[str, Any]
    vector: List[float]

    def __post_init__(self):
        """Validate required fields after initialization."""
        if not self.qdrant_point_id:
            raise ValueError("qdrant_point_id is required for StorageRecord")
        if not self.payload:
            raise ValueError("payload is required for StorageRecord")
        if not self.vector:
            raise ValueError("vector is required for StorageRecord")

    @classmethod
    def from_embedding_vector(
        cls,
        embedding_vector: EmbeddingVector,
        text_chunk: TextChunk,
        additional_metadata: Optional[Dict[str, Any]] = None
    ) -> 'StorageRecord':
        """
        Create a StorageRecord from an EmbeddingVector and TextChunk.

        Args:
            embedding_vector: The embedding vector
            text_chunk: The source text chunk
            additional_metadata: Additional metadata to include

        Returns:
            StorageRecord instance
        """
        payload = {
            "url": text_chunk.original_url,
            "chunk_id": text_chunk.chunk_id,
            "content": text_chunk.content,
            "section_title": text_chunk.section_title or "",
            "source_type": "docusaurus_page",
            "created_at": embedding_vector.created_at.isoformat(),
        }

        # Add any additional metadata
        if additional_metadata:
            payload.update(additional_metadata)

        # Generate a unique point ID for Qdrant
        point_id = str(uuid.uuid5(
            uuid.NAMESPACE_DNS,
            f"{embedding_vector.vector_id}_{embedding_vector.created_at.isoformat()}"
        ))

        return cls(
            qdrant_point_id=point_id,
            payload=payload,
            vector=embedding_vector.embedding
        )


@dataclass
class CrawlResult:
    """
    Represents the result of a crawling operation.
    """
    pages: List[DocusaurusPage]
    success_count: int
    failure_count: int
    total_time: float  # in seconds
    started_at: datetime = field(default_factory=datetime.now)
    completed_at: datetime = field(default_factory=datetime.now)

    def __post_init__(self):
        """Validate required fields after initialization."""
        if self.success_count < 0 or self.failure_count < 0:
            raise ValueError("success_count and failure_count must be non-negative")
        if len(self.pages) != (self.success_count + self.failure_count):
            raise ValueError("pages count must match sum of success and failure counts")


@dataclass
class EmbeddingResult:
    """
    Represents the result of an embedding operation.
    """
    embedding_vectors: List[EmbeddingVector]
    processed_chunks: int
    failed_chunks: int
    total_time: float  # in seconds
    started_at: datetime = field(default_factory=datetime.now)
    completed_at: datetime = field(default_factory=datetime.now)

    def __post_init__(self):
        """Validate required fields after initialization."""
        if self.processed_chunks < 0 or self.failed_chunks < 0:
            raise ValueError("processed_chunks and failed_chunks must be non-negative")
        if len(self.embedding_vectors) != self.processed_chunks:
            raise ValueError("embedding_vectors count must match processed_chunks")


@dataclass
class StorageResult:
    """
    Represents the result of a storage operation.
    """
    stored_records: int
    failed_records: int
    total_time: float  # in seconds
    started_at: datetime = field(default_factory=datetime.now)
    completed_at: datetime = field(default_factory=datetime.now)

    def __post_init__(self):
        """Validate required fields after initialization."""
        if self.stored_records < 0 or self.failed_records < 0:
            raise ValueError("stored_records and failed_records must be non-negative")